### ISSUE TITLE
Static

### ISSUE THREAD

**Issue by barakadax** [joeattardi/json-colorizer#29]
Hi, so I was wondering, for a project I'm doing for fun with C# Blazor I don't have NPM but I still want to use this, can you add a guide how to?

**Comment by joeattardi** [comment]
As this is only available as an npm package I'm not sure what other options you have. I have no experience with Blazor unfortunately.

I did find this, maybe it will help?

https://brianlagunas.com/using-npm-packages-in-blazor/

**Comment by barakadax** [comment]
If I want to take JS files and use it, what should I take to my project and if there is a license issue with it?
