### ISSUE TITLE
Feature: Coloring is different from pretty (:

### ISSUE THREAD

**Issue by NabiKAZ** [joeattardi/json-colorizer#38]
I noticed that besides coloring, it also arranges the bottom.
But this is just a coloring project.
So I think it's better to at least make `pretty` an option, that The output should be inline mode.
Something like this option:
```javascript
const jsonString = JSON.stringify(sampleJSON);
colorize(jsonString, { pretty: false });
                       ^^^^^^^^^^^^^
```

_P.S: And you might be interested that your project was suggested by artificial intelligence (:_

**Comment by joeattardi** [comment]
If you specify `indent: 0`, the JSON will not be pretty printed.
