### ISSUE TITLE
Thank you for building exactly what I needed

### ISSUE THREAD

**Issue by daxelrod** [joeattardi/json-colorizer#7]
You've built exactly what I needed, and saved me a bunch of effort.

I'm writing [a command line tool](https://github.com/daxelrod/jowl) that outputs JSON, and I've been wanting to add syntax-highlighted color output to it for a while.

In December 2015, nothing like `json-colorizer` existed, so I started writing one (with the same name, even). My efforts were blocked on [a feature to preserve whitespace](https://github.com/Floby/node-json-tokenizer/pull/3) in `node-json-tokenizer`, so I dropped it for a while.

Thank you! :bowing_man:

**Comment by joeattardi** [comment]
Thanks for the kind words! :smile:
