### ISSUE TITLE
2.1.0 Failed for WHITESPACE token type

### ISSUE THREAD

**Issue by myan9** [joeattardi/json-colorizer#9]
https://github.com/joeattardi/json-colorizer/blob/0351af4d8196b4c058f1a8677e6ded28c0f4146d/src/lib/colorizer.js#L21-L22

If I didn't provide customized colors options here, ```colorKeys``` should be ```undefined``` for ```WHITESPACE``` token type and then ```colorKey[0]``` fails naturally with ```TypeError: Cannot read property '0' of undefined```.

**Comment by joeattardi** [comment]
This was some lazy programming on my part! Sorry about that.

The issue should be fixed now in version 2.1.1. Let me know if you still have issues.
